CREATE TABLE `chec_db`.`housing_completion`
(
    `Geography (Province name)`	VARCHAR(512),
    `Geography (CMA name)`	VARCHAR(512),
    `Geography (CA name)`	VARCHAR(512),
    `Intended Market`	VARCHAR(512),
    `Type of House`	VARCHAR(512),
    `Year`	INT,
    `No of units`	VARCHAR(512)
);

INSERT INTO `chec_db`.`housing_completion` (`Geography (Province name)`, `Geography (CMA name)`, `Geography (CA name)`, `Intended Market`, `Type of House`, `Year`, `No of units`) VALUES
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '1990', '7'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '1991', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '1992', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '1993', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '1994', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '1995', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '1996', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '1997', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '1998', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '1999', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2000', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2001', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2002', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2003', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2004', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2005', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2006', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2007', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2008', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2009', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2010', '4'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2011', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2012', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2013', '12'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2014', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2015', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2016', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2017', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2018', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2019', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2020', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2021', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Row', '2022', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '1990', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '1991', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '1992', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '1993', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '1994', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '1995', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '1996', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '1997', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '1998', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '1999', '14'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2000', '8'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2001', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2002', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2003', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2004', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2005', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2006', '6'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2007', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2008', '8'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2009', '8'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2010', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2011', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2012', '10'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2013', '11'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2014', '19'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2015', '4'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2016', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2017', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2018', '4'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2019', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2020', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2021', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Row', '2022', '20'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '1990', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '1991', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '1992', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '1993', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '1994', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '1995', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '1996', '4'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '1997', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '1998', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '1999', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2000', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2001', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2002', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2003', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2004', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2005', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2006', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2007', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2008', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2009', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2010', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2011', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2012', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2013', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2014', '28'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2015', '16'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2016', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2017', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2018', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2019', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2020', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2021', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Row', '2022', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '1990', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '1991', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '1992', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '1993', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '1994', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '1995', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '1996', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '1997', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '1998', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '1999', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2000', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2001', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2002', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2003', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2004', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2005', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2006', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2007', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2008', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2009', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2010', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2011', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2012', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2013', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2014', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2015', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2016', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2017', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2018', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2019', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2020', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2021', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Row', '2022', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '1990', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '1991', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '1992', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '1993', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '1994', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '1995', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '1996', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '1997', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '1998', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '1999', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2000', '3'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2001', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2002', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2003', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2004', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2005', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2006', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2007', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2008', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2009', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2010', '18'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2011', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2012', '10'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2013', '16'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2014', '33'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2015', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2016', '8'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2017', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2018', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2019', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2020', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2021', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Row', '2022', '4'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '1990', '77'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '1991', '68'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '1992', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '1993', '8'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '1994', '16'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '1995', '20'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '1996', '3'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '1997', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '1998', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '1999', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2000', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2001', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2002', '3'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2003', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2004', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2005', '35'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2006', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2007', '3'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2008', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2009', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2010', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2011', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2012', '30'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2013', '5'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2014', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2015', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2016', '6'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2017', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2018', '42'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2019', '28'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2020', '4'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2021', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Row', '2022', '69'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '1990', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '1991', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '1992', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '1993', '8'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '1994', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '1995', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '1996', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '1997', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '1998', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '1999', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2000', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2001', '0'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2002', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2003', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2004', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2005', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2006', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2007', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2008', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2009', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2010', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2011', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2012', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2013', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2014', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2015', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2016', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2017', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2018', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2019', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2020', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2021', '10'),
	('Alberta', 'Edmonton', 'NA', 'Rental', 'Apartment', '2022', '10'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '1990', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '1991', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '1992', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '1993', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '1994', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '1995', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '1996', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '1997', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '1998', '12'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '1999', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2000', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2001', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2002', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2003', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2004', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2005', '36'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2006', '76'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2007', '24'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2008', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2009', '94'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2010', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2011', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2012', '127'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2013', '72'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2014', '229'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2015', '79'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2016', '4'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2017', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2018', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2019', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2020', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2021', '1'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Rental', 'Apartment', '2022', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '1990', '6'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '1991', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '1992', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '1993', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '1994', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '1995', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '1996', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '1997', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '1998', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '1999', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2000', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2001', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2002', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2003', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2004', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2005', '16'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2006', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2007', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2008', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2009', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2010', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2011', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2012', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2013', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2014', '109'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2015', '42'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2016', '45'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2017', '73'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2018', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2019', '27'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2020', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2021', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Rental', 'Apartment', '2022', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '1990', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '1991', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '1992', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '1993', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '1994', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '1995', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '1996', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '1997', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '1998', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '1999', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2000', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2001', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2002', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2003', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2004', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2005', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2006', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2007', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2008', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2009', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2010', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2011', '4'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2012', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2013', '94'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2014', '8'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2015', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2016', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2017', '28'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2018', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2019', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2020', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2021', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Rental', 'Apartment', '2022', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '1990', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '1991', '18'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '1992', '18'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '1993', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '1994', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '1995', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '1996', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '1997', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '1998', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '1999', '6'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2000', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2001', '16'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2002', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2003', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2004', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2005', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2006', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2007', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2008', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2009', '22'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2010', '16'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2011', '21'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2012', '4'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2013', '12'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2014', '16'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2015', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2016', '45'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2017', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2018', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2019', '34'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2020', '12'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2021', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Rental', 'Apartment', '2022', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '1990', '60'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '1991', '35'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '1992', '12'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '1993', '33'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '1994', '75'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '1995', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '1996', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '1997', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '1998', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '1999', '8'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2000', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2001', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2002', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2003', '4'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2004', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2005', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2006', '38'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2007', '12'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2008', '32'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2009', '0'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2010', '39'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2011', '155'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2012', '257'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2013', '438'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2014', '838'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2015', '714'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2016', '520'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2017', '391'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2018', '1008'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2019', '431'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2020', '226'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2021', '291'),
	('Saskatchewan', 'NA', 'Regina', 'Rental', 'Apartment', '2022', '157'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '1990', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '1991', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '1992', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '1993', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '1994', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '1995', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '1996', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '1997', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '1998', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '1999', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2000', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2001', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2002', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2003', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2004', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2005', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2006', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2007', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2008', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2009', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2010', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2011', '3'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2012', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2013', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2014', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2015', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2016', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2017', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2018', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2019', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2020', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2021', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Row', '2022', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '1990', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '1991', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '1992', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '1993', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '1994', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '1995', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '1996', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '1997', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '1998', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '1999', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2000', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2001', '0'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2002', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2003', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2004', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2005', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2006', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2007', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2008', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2009', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2010', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2011', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2012', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2013', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2014', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2015', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2016', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2017', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2018', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2019', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2020', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2021', '10'),
	('Alberta', 'Edmonton', 'NA', 'owner', 'Apartment', '2022', '10'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '1990', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '1991', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '1992', '3'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '1993', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '1994', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '1995', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '1996', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '1997', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '1998', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '1999', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2000', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2001', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2002', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2003', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2004', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2005', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2006', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2007', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2008', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2009', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2010', '3'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2011', '14'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2012', '19'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2013', '4'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2014', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2015', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2016', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2017', '4'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2018', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2019', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2020', '16'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2021', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Row', '2022', '16'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '1990', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '1991', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '1992', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '1993', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '1994', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '1995', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '1996', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '1997', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '1998', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '1999', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2000', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2001', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2002', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2003', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2004', '7'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2005', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2006', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2007', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2008', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2009', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2010', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2011', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2012', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2013', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2014', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2015', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2016', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2017', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2018', '6'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2019', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2020', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2021', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Row', '2022', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '1990', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '1991', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '1992', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '1993', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '1994', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '1995', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '1996', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '1997', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '1998', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '1999', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2000', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2001', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2002', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2003', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2004', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2005', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2006', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2007', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2008', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2009', '8'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2010', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2011', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2012', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2013', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2014', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2015', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2016', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2017', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2018', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2019', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2020', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2021', '6'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Row', '2022', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '1990', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '1991', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '1992', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '1993', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '1994', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '1995', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '1996', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '1997', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '1998', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '1999', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2000', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2001', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2002', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2003', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2004', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2005', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2006', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2007', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2008', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2009', '2'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2010', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2011', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2012', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2013', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2014', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2015', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2016', '4'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2017', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2018', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2019', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2020', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2021', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'owner', 'Apartment', '2022', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '1990', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '1991', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '1992', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '1993', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '1994', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '1995', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '1996', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '1997', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '1998', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '1999', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2000', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2001', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2002', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2003', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2004', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2005', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2006', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2007', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2008', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2009', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2010', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2011', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2012', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2013', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2014', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2015', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2016', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2017', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2018', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2019', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2020', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2021', '0'),
	('Saskatchewan', 'NA', 'Moose Jaw', 'owner', 'Apartment', '2022', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '1990', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '1991', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '1992', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '1993', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '1994', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '1995', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '1996', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '1997', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '1998', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '1999', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2000', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2001', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2002', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2003', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2004', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2005', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2006', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2007', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2008', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2009', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2010', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2011', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2012', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2013', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2014', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2015', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2016', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2017', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2018', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2019', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2020', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2021', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'owner', 'Apartment', '2022', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '1990', '7'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '1991', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '1992', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '1993', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '1994', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '1995', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '1996', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '1997', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '1998', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '1999', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2000', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2001', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2002', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2003', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2004', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2005', '4'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2006', '9'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2007', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2008', '15'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2009', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2010', '8'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2011', '3'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2012', '13'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2013', '41'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2014', '12'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2015', '8'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2016', '16'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2017', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2018', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2019', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2020', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2021', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Row', '2022', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '1990', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '1991', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '1992', '3'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '1993', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '1994', '5'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '1995', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '1996', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '1997', '3'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '1998', '10'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '1999', '23'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2000', '11'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2001', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2002', '15'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2003', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2004', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2005', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2006', '70'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2007', '89'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2008', '69'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2009', '26'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2010', '31'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2011', '72'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2012', '65'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2013', '119'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2014', '172'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2015', '60'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2016', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2017', '4'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2018', '23'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2019', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2020', '16'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2021', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Row', '2022', '36'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '1990', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '1991', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '1992', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '1993', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '1994', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '1995', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '1996', '4'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '1997', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '1998', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '1999', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2000', '7'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2001', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2002', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2003', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2004', '7'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2005', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2006', '27'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2007', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2008', '12'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2009', '10'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2010', '20'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2011', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2012', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2013', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2014', '39'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2015', '28'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2016', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2017', '18'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2018', '10'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2019', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2020', '6'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2021', '7'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Row', '2022', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '1990', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '1991', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '1992', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '1993', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '1994', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '1995', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '1996', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '1997', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '1998', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '1999', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2000', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2001', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2002', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2003', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2004', '8'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2005', '10'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2006', '10'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2007', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2008', '10'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2009', '23'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2010', '32'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2011', '13'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2012', '4'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2013', '22'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2014', '5'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2015', '5'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2016', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2017', '15'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2018', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2019', '3'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2020', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2021', '14'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Row', '2022', '4'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '1990', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '1991', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '1992', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '1993', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '1994', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '1995', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '1996', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '1997', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '1998', '12'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '1999', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2000', '3'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2001', '10'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2002', '16'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2003', '4'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2004', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2005', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2006', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2007', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2008', '22'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2009', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2010', '18'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2011', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2012', '22'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2013', '24'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2014', '33'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2015', '4'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2016', '12'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2017', '4'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2018', '3'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2019', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2020', '16'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2021', '8'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Row', '2022', '16'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '1990', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '1991', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '1992', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '1993', '8'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '1994', '15'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '1995', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '1996', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '1997', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '1998', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '1999', '15'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2000', '8'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2001', '0'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2002', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2003', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2004', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2005', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2006', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2007', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2008', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2009', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2010', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2011', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2012', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2013', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2014', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2015', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2016', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2017', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2018', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2019', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2020', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2021', '20'),
	('Alberta', 'Edmonton', 'NA', 'Total', 'Apartment', '2022', '20'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '1990', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '1991', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '1992', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '1993', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '1994', '28'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '1995', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '1996', '18'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '1997', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '1998', '12'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '1999', '18'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2000', '6'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2001', '24'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2002', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2003', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2004', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2005', '84'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2006', '124'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2007', '155'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2008', '81'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2009', '96'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2010', '111'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2011', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2012', '127'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2013', '72'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2014', '229'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2015', '79'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2016', '8'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2017', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2018', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2019', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2020', '0'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2021', '1'),
	('Saskatchewan', 'NA', 'Lloydminster', 'Total', 'Apartment', '2022', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '1990', '57'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '1991', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '1992', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '1993', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '1994', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '1995', '15'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '1996', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '1997', '33'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '1998', '12'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '1999', '12'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2000', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2001', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2002', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2003', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2004', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2005', '16'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2006', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2007', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2008', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2009', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2010', '24'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2011', '40'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2012', '15'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2013', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2014', '109'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2015', '54'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2016', '69'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2017', '89'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2018', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2019', '27'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2020', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2021', '0'),
	('Saskatchewan', 'NA', 'Moose jaw', 'Total', 'Apartment', '2022', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '1990', '14'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '1991', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '1992', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '1993', '17'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '1994', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '1995', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '1996', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '1997', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '1998', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '1999', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2000', '18'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2001', '18'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2002', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2003', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2004', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2005', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2006', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2007', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2008', '4'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2009', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2010', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2011', '4'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2012', '32'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2013', '115'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2014', '8'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2015', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2016', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2017', '82'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2018', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2019', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2020', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2021', '0'),
	('Saskatchewan', 'NA', 'North Battleford', 'Total', 'Apartment', '2022', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '1990', '6'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '1991', '18'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '1992', '18'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '1993', '12'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '1994', '32'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '1995', '25'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '1996', '25'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '1997', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '1998', '24'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '1999', '18'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2000', '29'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2001', '16'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2002', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2003', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2004', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2005', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2006', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2007', '16'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2008', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2009', '67'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2010', '34'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2011', '48'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2012', '4'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2013', '12'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2014', '38'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2015', '179'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2016', '97'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2017', '2'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2018', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2019', '58'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2020', '12'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2021', '0'),
	('Saskatchewan', 'NA', 'Prince Albert', 'Total', 'Apartment', '2022', '0');